#	$NetBSD: Makefile,v 1.1 2011/02/06 01:14:11 joerg Exp $

HOST_BUILD=

.include "${.PARSEDIR}/../llvm/Makefile.inc"

.include "${LLVM_TOPLEVEL}/Makefile.inc"
.include "${LLVM_TOPLEVEL}/include/Makefile"
