#	$NetBSD: Makefile,v 1.3 2010/08/11 14:50:38 pooka Exp $

.include "../Makefile.inc"

.PATH:	${S}/dev/acpi

KMOD=	acpiverbose
IOCONF=	acpiverbose.ioconf
SRCS=	acpi_verbose.c

.include <bsd.kmodule.mk>
