#	$NetBSD: Makefile,v 1.3 2001/12/12 12:24:21 lukem Exp $

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=		hostapd.conf
FILESDIR=	/usr/share/examples/hostapd
.endif

.include <bsd.prog.mk>
