#	$NetBSD: Makefile,v 1.3 2012/06/01 13:19:39 nonaka Exp $

NOMAN=	# defined

.include <bsd.own.mk>

.if ${MKFIRMWARE} != "no"
FILES=	rum-rt2573 rum-license
.endif

# XXX
includes:

clean:

cleandir:

.include <bsd.files.mk>
