# $NetBSD: Makefile,v 1.1 2011/05/03 08:36:15 jruoho Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/pr

TESTS_SH=	t_basic

FILESDIR=	${TESTSDIR}
FILES+=		d_basic.in
FILES+=		d_basic.out

.include <bsd.test.mk>
