#	$NetBSD: Makefile,v 1.6 2016/04/27 19:50:06 christos Exp $

NOMAN=	# defined

.include <bsd.own.mk>

.if ${MKFIRMWARE} != "no"
FILES=	ral-rt2561 ral-rt2561s ral-rt2661 ral-rt2860 ral-license
.endif

# XXX
includes:

clean:

cleandir:

.include <bsd.files.mk>
