#	$NetBSD: Makefile,v 1.1 2007/03/06 21:57:25 bouyer Exp $
CDBASE=		sun2cd			# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
