#	$NetBSD: Makefile,v 1.1 2012/06/01 13:19:39 nonaka Exp $

NOMAN=	# defined

.include <bsd.own.mk>

.if ${MKFIRMWARE} != "no"
FILES=	run-rt2870 run-rt3071 run-license
.endif

# XXX
includes:

clean:

cleandir:

.include <bsd.files.mk>
