# $NetBSD: Makefile,v 1.6 2009/06/03 18:47:06 bouyer Exp $

NOMAN=  # defined

# pull LOCALEDIR and other declarations
.include <bsd.own.mk>

LOCALEFILE=	LC_MESSAGES/SYS_LC_MESSAGES
CATEGORY=	messages

.include "${.CURDIR}/../Makefile.locale"
.include "${.CURDIR}/../Makefile.common"
