# $NetBSD: Makefile,v 1.1 2011/06/09 05:25:17 spz Exp $

HELPER_NAME=	evp_test
HELPER_DIR=	evp

FILES= \
evpcase.txt \
evpciph.txt \
evpdigest.txt \
evpencod.txt \
evpkdf.txt \
evpmac.txt \
evppbe.txt \
evppkey.txt \
evppkey_ecc.txt

.include <bsd.init.mk>
.PATH: ${OPENSSLSRC}/test/recipes/30-test_evp_data
