# $NetBSD: Makefile,v 1.6 2010/06/07 03:43:51 riz Exp $

TESTSDIR=	${TESTSBASE}/fs/cd9660
WARNS=		4
FILESDIR=	${TESTSDIR}

TESTS_SH=	t_high_ino_big_file
FILES=		pr_48787.image.bz2
UUDECODE_FILES= pr_48787.image.bz2

.include <bsd.test.mk>
