#!/bin/sh
#
# $NetBSD: ifwatchd,v 1.3 2003/06/24 09:32:46 martin Exp $
#

# PROVIDE: ifwatchd
# REQUIRE: mountcritremote syslogd
# BEFORE: SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="ifwatchd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"

