#!/bin/sh
#
# $NetBSD: moused,v 1.1 2001/10/29 23:25:01 augustss Exp $
#

# PROVIDE: moused
# REQUIRE: DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="moused"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
