#!/bin/sh
#
# $NetBSD: pflogd,v 1.3 2008/06/18 09:06:26 yamt Exp $
#

# PROVIDE: npfd
# REQUIRE: npf
# BEFORE:  SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="npfd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
