#!/bin/sh
#
# $NetBSD: powerd,v 1.1 2003/04/18 05:19:35 thorpej Exp $
#

# PROVIDE: powerd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="powerd"
rcvar=$name
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
