#	$NetBSD: Makefile,v 1.6 2001/12/12 00:07:49 tv Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

NOMAN=		# defined

PROG=		snscore
CPPFLAGS+=	-I${.CURDIR}/../snake
HIDEGAME=	hidegame

.include "../../Makefile.inc"
.include <bsd.prog.mk>
