#	$NetBSD: Makefile,v 1.5 2010/01/25 15:55:36 pooka Exp $
#

PROG=	rump_nqmfs

LDADD+=	-lrumpfs_mfs -lrumpfs_ffs

ISRUMP=		# affirmative
NOMAN=		# si, signor
RUMP_DISKFS=	# well, uh, yea, but there's ffs

.include <bsd.prog.mk>
