#	$NetBSD: Makefile,v 1.1 2017/04/17 08:59:37 riastradh Exp $
#

.PATH:	${.CURDIR}/../../../../dev/usb

LIB=	rumpdev_ualea
COMMENT=USB Araneus Alea II TRNG

IOCONF=	UALEA.ioconf

SRCS+=	ualea.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
