#	$NetBSD: Makefile,v 1.6 2014/08/08 15:19:51 isaki Exp $

# stand/netboot is identical with stand/boot
# except that the default kernel which loads is nfs.

PROG=		netboot
CPPFLAGS+=	-DNETBOOT

.include "../boot/Makefile"
