# $NetBSD: Makefile.linux,v 1.1 2016/06/08 01:16:35 christos Exp $
SRCS=mopprobe.c
OBJS=${SRCS:.c=.o}

LDLIBS+=../common/libcommon.a
CFLAGS+=-I../common

mopprobe: ${OBJS}

clean:
	rm -f ${OBJS} mopprobe
