#	$NetBSD: Makefile,v 1.5 2010/07/13 21:13:28 jmmv Exp $

.include <bsd.own.mk>

KMOD=   	k_helper2
KMODULEDIR=	${DESTDIR}/${TESTSBASE}/modules/${KMOD}

SRCS=   	k_helper2.c

ATFFILE=	no
NOMAN=		# defined

.include <bsd.test.mk>
.include <bsd.kmodule.mk>
