#	$NetBSD: Makefile,v 1.2 2002/12/08 20:20:04 thorpej Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}powerpc-mkbootimage
HOST_SRCDIR=	sys/arch/powerpc/stand/mkbootimage

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
