#	$NetBSD: Makefile,v 1.1 2004/07/28 09:17:31 skrll Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}hppa-mkboot
HOST_SRCDIR=	sys/arch/hppa/stand/mkboot

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
