#	$NetBSD: Makefile,v 1.1 2008/04/30 21:15:33 garbled Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}mkubootimage
HOST_SRCDIR=	usr.bin/mkubootimage

HOST_CPPFLAGS+= -I${.CURDIR}

.include "${.CURDIR}/../Makefile.host"
