#	$NetBSD: Makefile,v 1.2 2011/03/10 14:49:17 pooka Exp $
#

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/shmif_dumpbus
FILESDIR=	${TESTSDIR}

TESTS_SH=	t_basic

FILES+=		d_pcap.out.bz2.uue d_pkthdrs.out.bz2.uue shmbus.bz2.uue

.include <bsd.test.mk>
