#	$NetBSD: Makefile,v 1.10 2002/05/13 01:04:18 lukem Exp $

SUBDIR=		ramdisk .WAIT instkernel .WAIT bootfloppy.sysinst
# `floppy-root' cannot be used now, due to size issue.
#SUBDIR+=	bootfloppy.generic

TARGETS+=	release

.include <bsd.subdir.mk>
