#	$NetBSD: Makefile,v 1.1 2011/05/29 17:19:31 tsutsui Exp $
CDBASE=		zauruscd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
