#	$NetBSD: Makefile.inc,v 1.1 2011/02/06 01:14:12 joerg Exp $

HOSTPROG=	xz
HOST_SRCDIR=	external/public-domain/xz/bin/xz

.include "${.PARSEDIR}/../xz-include/Makefile.inc"

.include "${.CURDIR}/../Makefile.host"
