#	$NetBSD: Makefile,v 1.2 2008/11/25 18:41:57 christos Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}awk
HOST_SRCDIR=	external/historical/nawk/bin
HOST_CPPFLAGS+=	-D__EXTENSIONS__	# for isblank

.include "${.CURDIR}/../Makefile.host"
