#	$NetBSD: Makefile,v 1.11 2007/05/28 12:06:33 tls Exp $
#	from: @(#)Makefile	5.8 (Berkeley) 7/28/90

USE_FORT?= yes	# network client

PROG=		ypcat
SRCS=		ypalias_init.c ypcat.c
FILES=		nicknames
FILESDIR=	/var/yp
MAN=		ypcat.1 nicknames.5
.include <bsd.prog.mk>
