#	$NetBSD: Makefile,v 1.2 2009/02/18 10:51:17 hira Exp $

NOMAN=	# defined

.include <bsd.own.mk>

.if ${MKFIRMWARE} != "no"
FILES=	zyd-zd1211 zyd-zd1211b zd1211-license
.endif

# XXX
includes:

clean:

cleandir:

.include <bsd.files.mk>
