#	$NetBSD: Makefile,v 1.18 2002/04/04 22:59:33 lukem Exp $
#	@(#)Makefile	8.3 (Berkeley) 2/16/94

# optional first stage bootblocks
SUBDIR+=bootxx_cd9660 bootxx_ffs bootxx_lfs

# flash-based bootblocks
SUBDIR+=boot

.include <bsd.subdir.mk>
