#	$NetBSD: Makefile,v 1.3 2000/10/20 05:32:47 simonb Exp $

INCSDIR= /usr/include/dev/wscons

# Only install includes which are used by userland
INCS=	wsconsio.h wsdisplay_usl_io.h wsksymdef.h wsksymdef.h wsksymvar.h

.include <bsd.kinc.mk>
