#	$NetBSD: Makefile.miidevs,v 1.2 2000/05/08 13:25:34 augustss Exp $

.include <bsd.own.mk>

RM=	rm

miidevs.h: miidevs devlist2h.awk
	${RM} -f miidevs.h miidevs_data.h
	${TOOL_AWK} -f devlist2h.awk miidevs
