#	$NetBSD: Makefile,v 1.1 2002/02/13 07:54:23 yamt Exp $

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKNLS} != "no"
FILES=	nls.alias
FILESDIR=/usr/share/nls # XXX use NLSDIR?

.include <bsd.prog.mk>
.endif
