# $NetBSD: Makefile,v 1.1 2010/07/16 13:56:31 jmmv Exp $

NOMAN=		# defined

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/libposix

TESTS_SUBDIRS=	bsd
TESTS_SUBDIRS+=	posix1
TESTS_SUBDIRS+=	posix2

.include <bsd.test.mk>
