#	$NetBSD: Makefile,v 1.5 2001/12/12 12:24:21 lukem Exp $

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKSHARE} != "no"
FILES=	LINUX_MAKEDEV
FILESDIR=/usr/share/examples/emul/linux/etc
.endif

.include <bsd.prog.mk>
