/* $NetBSD$ */

/*
 * Automatically generated by ./genheaders.sh on Wed May 16 14:39:02 CEST 2018
 * Do not modify directly!
 */
#ifndef _USERMODE_FRAME_REGS_H
#define _USERMODE_FRAME_REGS_H

#if defined(__i386__)
#include "../../i386/include/frame_regs.h"
#elif defined(__x86_64__)
#include "../../amd64/include/frame_regs.h"
#elif defined(__arm__)
#include "../../arm/include/frame_regs.h"
#else
#error port me
#endif

#endif
