#	$NetBSD: Makefile,v 1.6 2002/12/23 17:23:13 jdolecek Exp $

.include "../Makefile.inc"

.PATH:	${S}/fs/adosfs

KMOD=	adosfs
SRCS=	adlookup.c adutil.c advfsops.c advnops.c

.include <bsd.kmodule.mk>
