#	$NetBSD: Makefile,v 1.1 2007/03/06 21:57:01 bouyer Exp $
CDBASE=		ews4800mipscd		# gives ${CDBASE}.iso
CDRELEASE=	true			# include $RELEASEDIR/$MACHINE
CDRELEASE_NODEBUG=	true

.include "${.CURDIR}/../../../common/Makefile.bootcd"
