#	$NetBSD: Makefile.tcdevs,v 1.1 1998/06/12 23:22:59 cgd Exp $

.include <bsd.own.mk>

tcdevs.h tcdevs_data.h: tcdevs devlist2h.awk
	/bin/rm -f tcdevs.h tcdevs_data.h
	${TOOL_AWK} -f devlist2h.awk tcdevs
