# $NetBSD: Makefile,v 1.1 2009/10/02 18:50:13 elad Exp $

.include "../Makefile.inc"

.PATH:	${S}/secmodel/extensions

KMOD=	secmodel_extensions
SRCS=	secmodel_extensions.c

.include <bsd.kmodule.mk>
