# $NetBSD: Makefile,v 1.5 2009/06/03 18:47:06 bouyer Exp $

NOMAN=	# defined

.PATH: ${.CURDIR}/generated

# pull LOCALEDIR and other declarations
.include <bsd.own.mk>

LOCALEFILE=	LC_NUMERIC
CATEGORY=	numeric

.include "${.CURDIR}/../Makefile.locale"
.include "${.CURDIR}/../Makefile.common"
