# $NetBSD: Makefile,v 1.4 2011/11/04 02:23:39 christos Exp $

# NOTE: please add all syscall-tests to tests/lib/libc/sys.

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/net/sys

TESTS_C+=	t_rfc6056

.include <bsd.test.mk>
