#	$NetBSD: Makefile.ops-h,v 1.2 2011/02/05 03:09:46 christos Exp $

ops.h: ops.def mkops Makefile.ops-h
	${_MKTARGET_CREATE}
	AWK=${TOOL_AWK:Q} ${HOST_SH} ${NETBSDSRCDIR}/usr.bin/xlint/lint1/mkops -h ${.ALLSRC:M*ops.def} > ${.TARGET}

CLEANFILES+=	ops.h
DPSRCS+=	ops.h

op.h: ops.h
