#	$NetBSD: Makefile,v 1.3 2001/10/25 02:23:21 thorpej Exp $

HOSTPROGNAME=	${MACHINE_GNU_PLATFORM}-lint2
HOST_SRCDIR=	usr.bin/xlint/lint2
HOST_BINDIR=	${TOOLDIR}/libexec

.include "${.CURDIR}/../Makefile.host"
