#	$NetBSD: Makefile,v 1.11 2002/01/23 21:06:28 scw Exp $

S=${.CURDIR}/../../../../

.include <bsd.hostinit.mk>

HOSTPROG=	wrtvid

# only needed during build
proginstall::

.include <bsd.hostprog.mk>
