#	$NetBSD: Makefile,v 1.9 2011/03/07 13:28:06 he Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}sortinfo
HOST_SRCDIR=	usr.bin/sortinfo

HOST_CPPFLAGS+=	-I. -I${TOOLDIR}/include/nbinclude

.include "${.CURDIR}/../Makefile.nbincludes"
.include "${.CURDIR}/../Makefile.host"
