# $NetBSD: Makefile,v 1.6 2009/06/03 18:47:07 bouyer Exp $

NOMAN=	# defined

.PATH: ${.CURDIR}/generated

# pull LOCALEDIR and other declarations
.include <bsd.own.mk>

LOCALEFILE=	LC_TIME
CATEGORY=	time

.include "${.CURDIR}/../Makefile.locale"
.include "${.CURDIR}/../Makefile.common"
